[workspace]
authors = ["mark-roelfsema <markroelfsema@dds.nl>"]
channels = ["conda-forge"]
name = "Downscaling"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
create_GADM_raster_0_5 = "python main.py --create_GADM_raster --resolution '0.5'"
create_GADM_raster_6 = "python main.py --create_GADM_raster --resolution '6'"

[dependencies]
python = "3.12.*"
pathlib = ">=1.0.1,<2"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.6,<4"
xarray = ">=2025.9.0,<2026"
rioxarray = ">=0.19.0,<0.20"
rasterio = ">=1.5.0,<2"
gdal = ">=3.12.2,<4"
proj = "*"
proj-data = "*"
pyproj = ">=3.7.2,<4"
affine = ">=2.4.0,<3"
dask = ">=2025.9.1,<2026"
leafmap = ">=0.52.4,<0.53"
geopandas = ">=1.1.1,<2"
geemap = ">=0.37.1,<0.38"
seaborn = ">=0.13.2,<0.14"
zarr = ">=3.1.3,<4"
scipy = ">=1.16.2,<2"
pip = ">=25.2,<26"
netcdf4 = ">=1.7.4,<2"
tqdm = ">=4.67.1,<5"
rpy2 = ">=3.6.4,<4"
earthengine-api = ">=1.7.17,<2"
cartopy = ">=0.25.0,<0.26"
cachetools = "<6.0.0"
google-cloud-storage = ">=3.9.0,<4"
gsutil = ">=5.36,<6"
memory_profiler = ">=0.61.0,<0.62"
pydeflate = ">=2.1.3, <3"

[tool.pixi.pypi-dependencies]
downscaling = { path = ".", editable = true }
wbdata = ">=1.0.0, <2"
pretty_errors = ">=1.2.25,<2"

[activation.env]
GDAL_DATA = "$CONDA_PREFIX/Library/share/gdal"
PROJ_DATA = "$CONDA_PREFIX/Library/share/proj"
PROJ_LIB = "$CONDA_PREFIX/Library/share/proj"
#GDAL_DATA = "$PIXI_ENVIRONMENT_ROOT/Library/share/gdal"
#PROJ_DATA = "$PIXI_ENVIRONMENT_ROOT/Library/share/proj"
#PROJ_LIB = "$PIXI_ENVIRONMENT_ROOT/Library/share/proj"
